load('data.mat')
expA = array2table(data_exp_A,"VariableNames",["Time"...
    "Pressure" "LVDT" "defA1" "defA2" "defA3"...
    "defB4" "defB5" "defB6"]);

expA.Pressure = 6894.76*expA.Pressure;

expB = array2table(data_exp_B,"VariableNames",["Time"...
    "defA1" "defA2" "defA3"...
    "defB4" "defB5" "defB6"]);
save('extract.mat','expA','expB')

% femapA = table(a,"VariableNames",["LVDT" ...
%     "Tensão x A" "Tensão y A" "Tensão xy A" ...
%     "Tensão x B" "Tensão y B" "Tensão xy B"]);
% 
% femapB = table("VariableNames",[...
%     "Tensão x A" "Tensão y A" "Tensão xy A"...
%     "Tensão x B" "Tensão y B" "Tensão xy B"...
%     "Momento x A" "Momento y A" "Momento xy A"...
%     "Momento x B" "Momento y B" "Momento xy B"]);
% femap_result = array2table([tens_A tens_B mmt_A mmt_B], ...
%         "VariableNames",["Tensão A" "Tensão B" ...
%         "Momento A" "Momento B"],"RowNames", ...
%         ["X" "Y" "XY"]);

clear